### ISSUE TITLE
你博客的导航栏的链接有错误

### ISSUE THREAD

**Issue by gaccob** [beMySun/bemysun.github.io#1]
![image](https://user-images.githubusercontent.com/4684354/83761625-25ad0000-a6a9-11ea-9f2e-e4129ccaaeec.png)

link到了 https://github.com/recoluan

**Comment by beMySun** [comment]
惊吓，竟然有人看...
这个博客， 是前几天周末没事在家随便弄的(其实就是想体验下vuePress和那个主题)， 用的时候，因为图片存储比较麻烦， 也不支持codeopen,  就不想在这里更新了。

兄弟想看的话， 可以到我的思否博客： https://segmentfault.com/u/scaukk

**Comment by gaccob** [comment]
其实是闲逛找简历时无意看到 :)

老哥要是有兴趣看看微信支付的全栈职位，可以加我微信（gaccob）联系哈~
jd 是这个：https://careers.tencent.com/jobdesc.html?postId=1158571757951520768

**Comment by beMySun** [comment]
哈哈， 可以， 也算是有缘， 等下加你。
